K8s env, best practice, container.info.over container.id
falcosecurity/falco pull request #1384
Opened 2020-09-08 14:49 UTC by epcim

**What type of PR is this?**

/kind rule-update

/area rules

**What this PR does / why we need it**:

In my case, I log to ES, I want all informations about running pods available within the alert/audit record. Output field of rule, frequently miss important informations (ie, namespace). container.info macro instead can provide bunch of usefull details if k8s is configured (otherwise it has fallback). 

It is then better, to log all details and have them either available on alerts.  

(Here I miss some clarification, havent found it documented, but it seems to me, that only details about an event, that are part of falcosidekick Outputfields (https://github.com/falcosecurity/falcosidekick/blob/master/outputs/alertmanager.go#L25) are the ones key=value between "()" of the output field of rule. Sorry I am lazy to find it again in src code - it might be bit different, but the truth is that alert does not have all event details.

**Which issue(s) this PR fixes**:
n/a

**Special notes for your reviewer**:
racionale here is as I cant get more details in alert, I do have need use flexible %container.info macro to give me all important (namespace, podname, ...)

**Does this PR introduce a user-facing change?**:

```release-note
Rules output contains more details for Kubernetes containers through `%container.info` macro.
```

2020-09-08 14:49 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/falco/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [55c38e5](https://github.com/falcosecurity/falco/commits/55c38e5223179581c342afa6b03b3158463da395) K8s, best practice, log container.info

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2020-09-08 14:49 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **mstemm**
You can assign the PR to them by writing `/assign @mstemm` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Ffalco).

<details open>
Needs approval from an approver in each of these files:

- **[rules/OWNERS](https://github.com/falcosecurity/falco/blob/master/rules/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["mstemm"]} -->

2020-09-08 14:49 UTC, poiana commented
Welcome @epcim! It looks like this is your first PR to falcosecurity/falco 🎉

2020-09-08 14:53 UTC, epcim commented
To change the rules, I have used these few SED cmds..https://github.com/epcim/falco/blob/container-info-dockerfile/docker/falco/Dockerfile#L113 (the targed branch is example, I do have different build pipeline)

2020-09-14 10:20 UTC, leogr reviewed
LGTM

2020-09-14 10:20 UTC, leogr approved these changes

2020-09-14 10:20 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: 09a0428db9f9efc78c828eecd9b3d55f61e6b5b5</details>

2020-09-14 10:20 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco/pull/1384#pullrequestreview-487616400" title="Approved">leogr</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Ffalco).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[rules/OWNERS](https://github.com/falcosecurity/falco/blob/master/rules/OWNERS)~~ [leogr]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-10-13 10:00 UTC, leodido reviewed
Thansk @epcim for sending this.

Could you please adjust the release-note block as per [contributing guidelines](https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md#rule-type) (it should theoretically list all the rules when you made changes) and rebase this on top of the master?

2020-10-13 11:12 UTC, epcim commented
> Thansk @epcim for sending this.
> 
> Could you please adjust the release-note block as per [contributing guidelines](https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md#rule-type) (it should theoretically list all the rules when you made changes) and rebase this on top of the master?
> 
> Anyways, I tend to agree with your changes but there's at least a point that we need to take into consideration.
> 
> When `container.info` is not available the output will contain its fallback. Is such fallback something like what we have now (eg., `container_id=<ID>`)?
> Could you provide a fallback example, please?

- ok will rebase
- technically it possibly touch many rules, so release-note this time needs to be "generic statement" but I will list few If catch them.
- as far as I remember, container.info is makro has `container_id=<ID>` as fallback

2020-10-19 14:52 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **leogr**
You can assign the PR to them by writing `/assign @leogr` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Ffalco).

<details open>
Needs approval from an approver in each of these files:

- **[rules/OWNERS](https://github.com/falcosecurity/falco/blob/master/rules/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["leogr"]} -->

2020-10-19 14:52 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **leogr**
You can assign the PR to them by writing `/assign @leogr` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Ffalco).

<details open>
Needs approval from an approver in each of these files:

- **[rules/OWNERS](https://github.com/falcosecurity/falco/blob/master/rules/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["leogr"]} -->

2020-10-19 15:03 UTC, epcim commented
@leodido so I have rebased + updated commit message. 

`Each rule change must be on its own commit...`
For obvious reason I want to avoid split this into series of 37 commits.

Modified rules are:
- Disallowed SSH Connection
- Unexpected outbound connection destination
- Unexpected inbound connection source
- Modify Shell Configuration File
- Read Shell Configuration File
- Schedule Cron Jobs
- Update Package Repository
- Read ssh information
- Write below etc
- Read sensitive file trusted after startup
- Write below rpm database
- Modify binary dirs
- Mkdir binary dirs
- System user interactive
- Terminal shell in container
- System procs network activity
- Program run with disallowed http proxy env
- Interpreted procs inbound network activity
- Interpreted procs outbound network activity
- Unexpected UDP Traffic
- User mgmt binaries
- Create files below dev
- Unexpected K8s NodePort Connection
- Netcat Remote Code Execution in Container
- Launch Suspicious Network Tool in Container
- Launch Suspicious Network Tool on Host
- Search Private Keys or Passwords
- Clear Log Activities
- Remove Bulk Data from Disk
- Create Hidden Files or Directories
- Launch Remote File Copy Tools in Container
- Create Symlink Over Sensitive Files
- Detect outbound connections to common miner pool ports
- Detect crypto miners using the Stratum protocol
- Packet socket created in container
- Network Connection outside Local Subnet
- Redirect STDOUT/STDIN to Network Connection in Container

2020-10-26 19:09 UTC, epcim commented
@leodido all ok?

2020-10-26 19:14 UTC, Kaizhe commented
I think `image=%container.image.repository` will be redundant if we have `container.info`
I have some concerns over replacing an output field, as it may breaks the consumer code who may parse by `container.id`

2020-10-27 22:41 UTC, leodido commented
@epcim I was referring to put them in the release-note block only in this case, not every rule change in its own commit clearly 😊 

I'm okay with the changes. But I also get the @Kaizhe point.

It's definitely something to discuss in the community call!

Thanks for your awesome contribution!

2020-10-27 22:49 UTC, leodido approved these changes

2020-10-27 22:49 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: 732888e29226bb7053c578b1ca574df7959330ab</details>

2020-10-27 22:49 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco/pull/1384#pullrequestreview-518207991" title="Approved">leodido</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Ffalco).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[rules/OWNERS](https://github.com/falcosecurity/falco/blob/master/rules/OWNERS)~~ [leodido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-10-28 13:07 UTC, fntlnz commented
Putting this on hold until we have two positive reviews, feel free to hold cancel once this is ready. I need to unblock the merge queue.

/hold

2020-10-28 15:35 UTC, leodido commented
Two questions from @ldegio  (during our Falco Community Calls) today:

- why we can't just retain `container_id=%container.id` field and just append `%container.info` after it?
- what is the typical format of a `%container.info`? does it contains a JSON object, tuples, what?

Because maybe, disregarding eventual container ID duplication, this could be the way to go to also take care of the @Kaizhe's legit concerns.

2020-10-28 17:06 UTC, Kaizhe commented
> Two questions from @ldegio (during our Falco Community Calls) today:
> 
> * why we can't just retain `container_id=%container.id` field and just append `%container.info` after it?
> * what is the typical format of a `%container.info`? does it contains a JSON object, tuples, what?
> 
> Because maybe, disregarding eventual container ID duplication, this could be the way to go to also take care of the @Kaizhe's legit concerns.

Appending `container.info` in the output looks good to me

2020-10-28 17:07 UTC, Kaizhe requested changes
Please append `container.info` instead of replacing `container.id`

2020-11-02 08:01 UTC, epcim commented
> container.info 

`vs container.id vs. id=...`

So do we need any other default than? https://github.com/falcosecurity/falco/blob/3693b16c917d6920adffac03e80d38c1b64317ea/userspace/engine/lua/rule_loader.lua#L694


> I have some concerns over replacing an output field, as it may breaks the consumer code who may parse by `container.id`

As long as `container.info` has fallback to `container.id` and as long as it containse container.id, thats not an issue:

2020-11-02 08:15 UTC, Kaizhe commented
> > container.info
> 
> `vs container.id vs. id=...`
> 
> So do we need any other default than?
> 
> https://github.com/falcosecurity/falco/blob/3693b16c917d6920adffac03e80d38c1b64317ea/userspace/engine/lua/rule_loader.lua#L694
> 
> > I have some concerns over replacing an output field, as it may breaks the consumer code who may parse by `container.id`
> 
> As long as `container.info` has fallback to `container.id` and as long as it containse container.id, thats not an issue:

Can you confirm I can use the same json pointer(I don't need to change anything, e.g. pointer name, level) to get the container ID if you use `container.info`?

2020-11-02 10:46 UTC, epcim commented
> > > container.info
> > 
> > 
> > `vs container.id vs. id=...`
> > So do we need any other default than?
> > https://github.com/falcosecurity/falco/blob/3693b16c917d6920adffac03e80d38c1b64317ea/userspace/engine/lua/rule_loader.lua#L694
> > 
> > > I have some concerns over replacing an output field, as it may breaks the consumer code who may parse by `container.id`
> > 
> > 
> > As long as `container.info` has fallback to `container.id` and as long as it contains container.id, thats not an issue:
> 
> Can you confirm I can use the same json pointer(I don't need to change anything, e.g. pointer name, level) to get the container ID if you use `container.info`?

Seems like, but somebody else better to confirm. I am not Falco developer, just contributor. Macro `container.info` need some ownership and as you suggested it req. to be backward compatible, future support and notify existing users early if any change in behaviour.

Also `image=%container.image.repository will be redundant` is still not fixed. Having some filter that would uniq. filter keys of `extra_` would be handy.

2021-01-20 16:06 UTC, poiana commented
@epcim: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-01-20 16:41 UTC, epcim commented
I wont do rebase anymore.On 20 Jan 2021 17:06, poiana <notifications@github.com> wrote:
@epcim: PR needs rebase.

Instructions for interacting with me using PR comments are available here.  If you have questions or suggestions related to my behavior, please file an issue against the kubernetes/test-infra repository.


—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

2021-04-09 08:47 UTC, leodido commented
/milestone 0.28.1

2021-09-15 08:51 UTC, poiana commented
Issues go stale after 90d of inactivity.

Mark the issue as fresh with `/remove-lifecycle stale`.

Stale issues rot after an additional 30d of inactivity and eventually close.

If this issue is safe to close now please do so with `/close`.

Provide feedback via https://github.com/falcosecurity/community.

/lifecycle stale

2021-11-28 03:13 UTC, poiana commented
Rotten issues close after 30d of inactivity.

Reopen the issue with `/reopen`.

Mark the issue as fresh with `/remove-lifecycle rotten`.

Provide feedback via https://github.com/falcosecurity/community.
/close

2021-11-28 03:13 UTC, poiana commented
@poiana: Closed this PR.

<details>

In response to [this](https://github.com/falcosecurity/falco/pull/1384#issuecomment-980829381):

>Rotten issues close after 30d of inactivity.
>
>Reopen the issue with `/reopen`.
>
>Mark the issue as fresh with `/remove-lifecycle rotten`.
>
>Provide feedback via https://github.com/falcosecurity/community.
>/close


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-11-28 03:13 UTC, closed without merging