Update falco_rules.yaml
falcosecurity/falco pull request #1543
Opened 2021-01-28 20:08 UTC by darryk5

Added Rule Sudo Potential Privilege Escalation (CVE-2021-3156)
Open Issue https://github.com/falcosecurity/falco/issues/1540

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

> /kind rule-update

> /kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area engine

> /area rules

> /area tests

> /area proposals

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2021-01-28 20:08 UTC, poiana commented
@darryk5: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-01-28 20:08 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/falco/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [e42ec08](https://github.com/falcosecurity/falco/commits/e42ec08a40e52fa3cfe5799bb69978bfa160af4d) Update falco_rules.yaml

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-01-28 20:08 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **mstemm** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @mstemm` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Ffalco).

<details open>
Needs approval from an approver in each of these files:

- **[rules/OWNERS](https://github.com/falcosecurity/falco/blob/master/rules/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["mstemm"]} -->

2021-01-28 20:08 UTC, poiana commented
Welcome @darryk5! It looks like this is your first PR to falcosecurity/falco 🎉

2021-01-28 20:17 UTC, Kaizhe requested changes

2021-01-28 20:17 UTC, Kaizhe commented on rules/falco_rules.yaml
> +  output: "Detect Sudo Privilege Escalation Exploit (CVE-2021-3156)  (user=%user.name  %container.info parent=%proc.pname cmdline=%proc.cmdline)"
there is an extra space character between `%user.name` and `%container.info`.

And let's move `%container.info` to the end of the output as it may not happen inside a container.

2021-01-28 20:19 UTC, Kaizhe commented
#1540

2021-01-28 20:24 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/falco/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [e42ec08](https://github.com/falcosecurity/falco/commits/e42ec08a40e52fa3cfe5799bb69978bfa160af4d) Update falco_rules.yaml
- [2a20f9b](https://github.com/falcosecurity/falco/commits/2a20f9b0d2f01e85c8db61ef47e392703c030bb8) Update falco_rules.yaml

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-01-28 20:24 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **kaizhe** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @kaizhe` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Ffalco).

<details open>
Needs approval from an approver in each of these files:

- **[rules/OWNERS](https://github.com/falcosecurity/falco/blob/master/rules/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["kaizhe"]} -->

2021-01-28 20:25 UTC, darryk5 reviewed
Moved %container.info at the end as suggested by @Kaizhe

2021-01-28 22:24 UTC, Kaizhe commented
@darryk5 please sign your commits and update release notes with the following fomrat:
```
rule(list user_known_change_thread_namespace_binaries): add crio and multus to the list
```

2021-01-28 22:25 UTC, Kaizhe reviewed
lgtm, thanks! Please address my other comments in the thread

2021-01-28 22:47 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/falco/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [e42ec08](https://github.com/falcosecurity/falco/commits/e42ec08a40e52fa3cfe5799bb69978bfa160af4d) Update falco_rules.yaml

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-01-28 23:22 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **mstemm** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @mstemm` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Ffalco).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falco/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["mstemm"]} -->

2021-01-29 09:24 UTC, leodido requested changes
Needs some refinements IMHO, but thanks for submitting it

2021-01-29 09:24 UTC, leodido commented on CHANGELOG.md
> +* rule(Sudo Potential Privilege Escalation (CVE-2021-3156)): new rule created to detect CVE-2021-3156[[#1543](https://github.com/falcosecurity/falco/pull/1543)] - [@darryk5](https://github.com/darryk
Changelog must not be changed manually.

It gets automatically compiled from the `release-notes` block in the PR template.

2021-01-29 09:24 UTC, leodido commented on rules/falco_rules.yaml
> +- rule: Sudo Potential Privilege Escalation (CVE-2021-3156)
```suggestion
// This rule helps detect CVE-2021-3156:
// A privilege escalation to root through heap-based buffer overflow
- rule: Sudo Potential Privilege Escalation 
```

Would you please accept my suggestion here?

2021-01-29 09:24 UTC, leodido commented on rules/falco_rules.yaml
> +  desc: Privilege escalation vulnerability affected sudo. Executing sudo using sudoedit -s or sudoedit -t command from an unprivileged user it's possible to elevate the user privileges to root.
Not totally correct.

To happen 

```suggestion
  desc: Privilege escalation vulnerability affecting sudo (<= 1.9.5p2). Executing sudo using sudoedit -s or sudoedit -i command with command-line argument that ends with a single backslash character from an unprivileged user it's possible to elevate the user privileges to root.
```

Would you also accept my suggestion here

2021-01-29 09:24 UTC, leodido commented on rules/falco_rules.yaml
> +  condition: spawned_process and user.uid!= 0 and proc.name=sudoedit and (proc.args contains -s or proc.args contains -i) and (proc.args contains "\ " or proc.args endswith \)
Is the space in "\ " wanted here?

2021-01-29 09:41 UTC, leogr requested changes
Overall the rule is ok. However, I found some issues (see comments).

Moreover, since this rule derives from @fntlnz's work (posted in https://github.com/falcosecurity/falco/issues/1540), I believe the commit should include the right attribution (i.e. `Co-Authored-By`). Also, squashing the two comments into one would be better, IMHO.

Thanks.

2021-01-29 09:41 UTC, leogr commented on CHANGELOG.md
> +* rule(Sudo Potential Privilege Escalation (CVE-2021-3156)): new rule created to detect CVE-2021-3156[[#1543](https://github.com/falcosecurity/falco/pull/1543)] - [@darryk5](https://github.com/darryk
```suggestion
```

This patch will be not included in 0.27.0. Most important, do not modify the CHANGELOG.md manually, please. 
The changelog will be updated in the release process as described [here](https://github.com/falcosecurity/falco/blob/master/RELEASE.md#pre-release-checklist)

2021-01-29 09:41 UTC, leogr commented on rules/falco_rules.yaml
> +  output: "Detect Sudo Privilege Escalation Exploit (CVE-2021-3156)  (user=%user.name parent=%proc.pname cmdline=%proc.cmdline %container.info)"
```suggestion
  output: "Detect Sudo Privilege Escalation Exploit (CVE-2021-3156) (user=%user.name parent=%proc.pname cmdline=%proc.cmdline %container.info)"
```

2021-01-29 09:41 UTC, leogr commented on rules/falco_rules.yaml
> +
```suggestion
```

2021-01-29 09:41 UTC, leogr commented on rules/falco_rules.yaml
> +
Unnecessary newlines.

2021-01-29 09:41 UTC, leogr commented on rules/falco_rules.yaml
> +  output: "Detect Sudo Privilege Escalation Exploit (CVE-2021-3156)  (user=%user.name parent=%proc.pname cmdline=%proc.cmdline %container.info)"
Unnecessary space here.

2021-01-29 09:41 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **leodido** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @leodido` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Ffalco).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falco/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["leodido"]} -->

2021-01-29 11:08 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/falco/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [1eda443](https://github.com/falcosecurity/falco/commits/1eda44380ef32c73684c24c8cd1dff2c6c221d50) fix
- [a433d08](https://github.com/falcosecurity/falco/commits/a433d0837d88e0322476412d45f453b68b57c885) Fix CHANGELOG.md

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-01-29 11:08 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **kaizhe** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @kaizhe` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Ffalco).

<details open>
Needs approval from an approver in each of these files:

- **[rules/OWNERS](https://github.com/falcosecurity/falco/blob/master/rules/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["kaizhe"]} -->

2021-01-29 11:12 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/falco/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [1eda443](https://github.com/falcosecurity/falco/commits/1eda44380ef32c73684c24c8cd1dff2c6c221d50) fix

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-01-29 11:17 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/falco/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [1eda443](https://github.com/falcosecurity/falco/commits/1eda44380ef32c73684c24c8cd1dff2c6c221d50) fix
- [ce0cc41](https://github.com/falcosecurity/falco/commits/ce0cc4155423caeb2bc5e02eaaee4c1b79904785) Merge branch 'patch-1' of https://github.com/darryk5/falco into patch-1

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-01-29 11:17 UTC, poiana commented
@darryk5: Adding label `do-not-merge/contains-merge-commits` because PR contains merge commits, which are not allowed in this repository.
Use `git rebase` to reapply your commits on top of the target branch. Detailed instructions for doing so can be found [here](https://git.k8s.io/community/contributors/guide/github-workflow.md#4-keep-your-branch-in-sync).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-01-29 11:19 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/falco/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [1eda443](https://github.com/falcosecurity/falco/commits/1eda44380ef32c73684c24c8cd1dff2c6c221d50) fix

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-01-29 11:54 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **leodido** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @leodido` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Ffalco).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falco/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["leodido"]} -->

2021-01-29 12:17 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **kaizhe** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @kaizhe` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Ffalco).

<details open>
Needs approval from an approver in each of these files:

- **[rules/OWNERS](https://github.com/falcosecurity/falco/blob/master/rules/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["kaizhe"]} -->

2021-01-29 12:59 UTC, darryk5 commented on rules/falco_rules.yaml
> +  condition: spawned_process and user.uid!= 0 and proc.name=sudoedit and (proc.args contains -s or proc.args contains -i) and (proc.args contains "\ " or proc.args endswith \)
Since filter proc.args, it concatenate all the arguments together as a single string and separated by space character with "\ ", we cover the arguments ending with \ in the middle.

2021-02-11 11:41 UTC, deepskyblue86 commented
I agree with @leogr, would you please squash the commits into a single one?

2021-02-17 07:34 UTC, leogr commented
/milestone 0.28.0

2021-02-17 07:41 UTC, leogr approved these changes

2021-02-17 07:41 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: 8b85842ff2e1ac9f68e864c059d9573a0628dbce</details>

2021-02-17 07:41 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco/pull/1543#pullrequestreview-591907927" title="Approved">leogr</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Ffalco).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[rules/OWNERS](https://github.com/falcosecurity/falco/blob/master/rules/OWNERS)~~ [leogr]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-02-17 14:38 UTC, leodido approved these changes

2021-02-17 14:38 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco/pull/1543#pullrequestreview-592262587" title="Approved">leodido</a>*, *<a href="https://github.com/falcosecurity/falco/pull/1543#pullrequestreview-591907927" title="Approved">leogr</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Ffalco).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[rules/OWNERS](https://github.com/falcosecurity/falco/blob/master/rules/OWNERS)~~ [leodido,leogr]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-02-17 16:57 UTC, leogr commented
/cc @Kaizhe 
PTAL

2021-02-17 20:36 UTC, Kaizhe approved these changes

2021-02-17 20:36 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco/pull/1543#pullrequestreview-592605381" title="Approved">Kaizhe</a>*, *<a href="https://github.com/falcosecurity/falco/pull/1543#pullrequestreview-592262587" title="Approved">leodido</a>*, *<a href="https://github.com/falcosecurity/falco/pull/1543#pullrequestreview-591907927" title="Approved">leogr</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Ffalco).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[rules/OWNERS](https://github.com/falcosecurity/falco/blob/master/rules/OWNERS)~~ [Kaizhe,leodido,leogr]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-02-17 20:36 UTC, merged