wip: rules(Netcat Remote Code Execution in Container): Add space to validate arguments
falcosecurity/falco pull request #1593
Opened 2021-03-26 20:26 UTC by Carlangueitor

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

> /kind rule-update

> /kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area engine

/area rules

> /area tests

> /area proposals

**What this PR does / why we need it**:
This rule raises some false-positive when using a hostname with `-e` or `-c`, e.g `nc -q 1 some-endpoint 3000`. Adding the space validates that is an actual argument ar not part of other argument.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2021-03-26 20:26 UTC, poiana commented
@Carlangueitor: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-03-26 20:26 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/falco/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [f6c12fe](https://github.com/falcosecurity/falco/commits/f6c12fed8c044fc7e13451796cd1e4345e053e4e) rules(Netcat Remote Code Execution in Container): Add space to validate arguments

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-03-26 20:26 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **mstemm** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @mstemm` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Ffalco).

<details open>
Needs approval from an approver in each of these files:

- **[rules/OWNERS](https://github.com/falcosecurity/falco/blob/master/rules/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["mstemm"]} -->

2021-03-26 20:26 UTC, poiana commented
Welcome @Carlangueitor! It looks like this is your first PR to falcosecurity/falco 🎉

2021-03-26 20:26 UTC, poiana commented
Hi @Carlangueitor. Thanks for your PR.

I'm waiting for a [falcosecurity](https://github.com/orgs/falcosecurity/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/falcosecurity/.github/blob/master/GOVERNANCE.md) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Ffalco).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-03-29 09:16 UTC, leodido reviewed
Hello @Carlangueitor could you please sign-off your commit? 

Instructions [here](https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md#developer-certificate-of-origin) in case you need them :)

/cc @Kaizhe

2021-03-29 09:16 UTC, leodido commented
/milestone 0.28.0

2021-03-29 17:49 UTC, Kaizhe requested changes
Thanks for the contribution 👍

2021-03-29 17:49 UTC, Kaizhe commented on rules/falco_rules.yaml
> +     (proc.name = "ncat" and (proc.args contains "--sh-exec" or proc.args contains "--exec" or proc.args contains " -e "
@Carlangueitor can you please also put a space after `-e` and `-c` too? So as to `--sh-exec`, `--exec` and `--lua-exec`

2021-03-29 17:49 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **mstemm** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @mstemm` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco).

<details open>
Needs approval from an approver in each of these files:

- **[rules/OWNERS](https://github.com/falcosecurity/falco/blob/master/rules/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["mstemm"]} -->

2021-04-09 08:41 UTC, leodido commented
/milestone 0.28.1

2021-04-11 15:36 UTC, poiana commented
@Carlangueitor: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-09-15 14:51 UTC, poiana commented
Issues go stale after 90d of inactivity.

Mark the issue as fresh with `/remove-lifecycle stale`.

Stale issues rot after an additional 30d of inactivity and eventually close.

If this issue is safe to close now please do so with `/close`.

Provide feedback via https://github.com/falcosecurity/community.

/lifecycle stale

2021-11-28 09:13 UTC, poiana commented
Rotten issues close after 30d of inactivity.

Reopen the issue with `/reopen`.

Mark the issue as fresh with `/remove-lifecycle rotten`.

Provide feedback via https://github.com/falcosecurity/community.
/close

2021-11-28 09:13 UTC, poiana commented
@poiana: Closed this PR.

<details>

In response to [this](https://github.com/falcosecurity/falco/pull/1593#issuecomment-981050563):

>Rotten issues close after 30d of inactivity.
>
>Reopen the issue with `/reopen`.
>
>Mark the issue as fresh with `/remove-lifecycle rotten`.
>
>Provide feedback via https://github.com/falcosecurity/community.
>/close


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-11-28 09:13 UTC, closed without merging