rule to detect successful unprivileged userfaultfd events
falcosecurity/falco pull request #1675
Opened 2021-06-11 13:26 UTC by leodido

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

 /kind feature

/kind rule-update

/kind rule-create

**Any specific area of the project related to this PR?**

/area rules

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Refs #676 

**Special notes for your reviewer**:

To try it out you need to build Falco against [this branch in libs](https://github.com/falcosecurity/libs/pull/50).

Holding this PR until that branch is merged into libs.

/hold

Also, while doing this PR I took the chance to include a simple addition on the rule detecting kernel module injections from containers: it was missing the container info in the output, I added it.

**Does this PR introduce a user-facing change?**:

```release-note
rule(Unprivileged Delegation of Page Faults Handling to a Userspace Process): new rule to detect successful unprivileged userfaultfd syscalls
rule(Linux Kernel Module Injection Detected): adding container info to the output of the rule
```

2021-06-11 13:26 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco/pull/1675#" title="Author self-approved">leodido</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[rules/OWNERS](https://github.com/falcosecurity/falco/blob/master/rules/OWNERS)~~ [leodido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-06-11 13:36 UTC, leodido commented
/milestone 0.29.0

(temptatively)

2021-06-11 15:54 UTC, Kaizhe commented on rules/falco_rules.yaml
> +    evt.type = userfaultfd and
Is this syscall `userfaultfd` available to consume now? I didn't find it in the syscall table.

2021-06-11 16:52 UTC, leodido commented on rules/falco_rules.yaml
> +    evt.type = userfaultfd and
Hey @Kaizhe, as written in the PR corpus, such a syscall would be available once https://github.com/falcosecurity/libs/pull/50 gets merged in :)

2021-06-11 16:53 UTC, leodido commented on rules/falco_rules.yaml
> +    evt.type = userfaultfd and
To test this PR is sufficient changing `cmake/modules/falcosecurity-libs.cmake` to point to the branch of that PR (also changing the SHA256 hash or de-commenting it just for testing purposes).

2021-06-11 17:21 UTC, Kaizhe requested changes

2021-06-11 17:21 UTC, Kaizhe commented on rules/falco_rules.yaml
> +    evt.type = userfaultfd and
Cool! I missed that, can we have a custom macro for the rule say `user_known_user_faultfd_activities` with condition `never_true`?

2021-06-11 17:21 UTC, Kaizhe commented on rules/falco_rules.yaml
> +- rule: Unprivileged Delegation of Page Faults Handling to a Userspace Process
need to bump the rule engine version?

2021-06-11 17:21 UTC, Kaizhe commented on rules/falco_rules.yaml
> +  tags: [process, mitre_defense_evasion]
I would prefer the tag it as `syscall` instead of `process`

2021-06-15 10:24 UTC, leodido commented on rules/falco_rules.yaml
> +- rule: Unprivileged Delegation of Page Faults Handling to a Userspace Process
Yes, right! Thanks for reminding me :)

2021-06-15 10:31 UTC, leodido commented on rules/falco_rules.yaml
> +    evt.type = userfaultfd and
Indeed we can.

It seems to me it's a good suggestion!

2021-06-15 10:42 UTC, leogr commented
I have updated https://github.com/falcosecurity/falco/pull/1669 
It now includes the driver version required to support these rules.

2021-06-15 18:24 UTC, Kaizhe commented on rules/falco_rules.yaml
> +  condition: >
just had another thought,

1. Maybe we should limit the attack scenario in container as gaining into the node is a high privileged access. 
2. If we can assume the attack scenario in container, we may want to detect `userfaultfd` by all users including root, especially people still run `root` containers quite commonly nowadays.

2021-06-17 12:11 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco/pull/1675#" title="Author self-approved">leodido</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/falco/blob/master/OWNERS)~~ [leodido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-06-17 12:11 UTC, leodido commented on rules/falco_rules.yaml
> +  tags: [process, mitre_defense_evasion]
Done

2021-06-17 12:59 UTC, leodido commented
Rebased to let the CI pick latest changes (needed) from the master branch

2021-06-18 20:59 UTC, Kaizhe commented on rules/falco_rules.yaml
> +    consider_userfaultfd_activities and
Are we going to see some warning message thrown by Falco since the condition not started with `evt.type` filter.

2021-06-21 09:12 UTC, leodido commented on rules/falco_rules.yaml
> +    consider_userfaultfd_activities and
Hey @Kaizhe nope! :)

The Falco engine emits a warning IF an `evt.type` filter is missing at all, not if before it there's a macro. In fact, we have various rules using this pattern: a macro acting as a gate (value `never_true` or `always_true`) before the filter on the event type.

2021-06-21 18:32 UTC, Kaizhe commented on rules/falco_rules.yaml
> +    consider_userfaultfd_activities and
Thanks!

2021-06-21 18:32 UTC, Kaizhe commented on rules/falco_rules.yaml
> +  condition: >
@leodido let me know what you think

2021-06-21 23:06 UTC, Kaizhe approved these changes

2021-06-22 13:58 UTC, leogr approved these changes

2021-06-23 08:43 UTC, leogr commented
/hold cancel

2021-06-23 08:44 UTC, merged

2021-06-28 07:59 UTC, leodido commented
/milestone 0.29.1