Allow append of new exceptions to rules
falcosecurity/falco pull request #1780
Opened 2021-11-10 18:19 UTC by sai-arigeli

Signed-off-by: Mark Stemm <mark.stemm@gmail.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

> /kind rule-update

> /kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area engine

/area rules

> /area tests

> /area proposals

**What this PR does / why we need it**:
PR introduces appending of new fully valid exception objects to existing rules.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2021-11-10 18:19 UTC, poiana commented
@sai-arigeli: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-11-10 18:19 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco/pull/1780#" title="Author self-approved">sai-arigeli</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **fntlnz** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @fntlnz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falco/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["fntlnz"]} -->

2021-11-10 18:45 UTC, leodido reviewed
Before reviewing... Why the commit comes from a GitHub user that sign-offs commit with @mstemm email?

2021-11-10 18:45 UTC, leodido commented
I refer to this:

![image](https://user-images.githubusercontent.com/120051/141174319-80d3449b-1f75-4207-8284-3f2c3a2579d7.png)

2021-11-10 18:54 UTC, leodido commented
The DCO (implemented via the sign-off) requires the contributor's email (not another one) AFAIK

2021-11-10 19:24 UTC, sai-arigeli commented
> The DCO (implemented via the sign-off) requires the contributor's email (not another one) AFAIK

@leodido I had wrongly infered that sign-off needs to be one of the owner. I corrected the commit message.

2021-11-11 18:35 UTC, leodido commented
@sai-arigeli I was not understanding because looking at your fork/other PRs via the GitHub events I saw that you were signing-off correctly there (sysdig or gmail email)...

![image](https://user-images.githubusercontent.com/120051/141350987-ca3da3ef-8b29-4b05-96aa-c5b12b193f7c.png)

2021-11-12 11:01 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco/pull/1780#" title="Author self-approved">sai-arigeli</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **mstemm** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falco/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["mstemm"]} -->

2021-11-12 11:06 UTC, sai-arigeli commented on userspace/engine/lua/rule_loader.lua
> +			   return valid, err
@mstemm the 'err' here is already built with context inside the called rule validate functions. I've added 'warnings' to return parameters.

2021-11-12 16:03 UTC, mstemm commented on userspace/engine/lua/rule_loader.lua
> +			   return valid, err
Great thx!

2021-11-12 16:04 UTC, mstemm approved these changes

2021-11-12 16:51 UTC, leogr commented
Closing and reopening to trigger the CI
/close

2021-11-12 16:51 UTC, poiana commented
@leogr: Closed this PR.

<details>

In response to [this](https://github.com/falcosecurity/falco/pull/1780#issuecomment-967263565):

>Closing and reopening to trigger the CI
>/close


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-11-12 16:51 UTC, leogr commented
/reopen

2021-11-12 16:51 UTC, poiana commented
@leogr: Reopened this PR.

<details>

In response to [this](https://github.com/falcosecurity/falco/pull/1780#issuecomment-967263652):

>/reopen


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-11-12 16:52 UTC, leogr commented
/milestone 0.31.0

2021-11-12 20:49 UTC, mstemm requested changes
I thought of another change--since this changes the behavior of how falco reads rules files, you should bump the falco engine version here: https://github.com/falcosecurity/falco/blob/master/userspace/engine/falco_engine_version.h#L19. Can you increment it to 11?

2021-11-12 21:23 UTC, poiana commented
@sai-arigeli: Adding label `do-not-merge/contains-merge-commits` because PR contains merge commits, which are not allowed in this repository.
Use `git rebase` to reapply your commits on top of the target branch. Detailed instructions for doing so can be found [here](https://git.k8s.io/community/contributors/guide/github-workflow.md#4-keep-your-branch-in-sync).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-11-12 21:23 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/falco/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [826bbcd](https://github.com/falcosecurity/falco/commits/826bbcd6d04981a5128f89681003561ac6d6716a) Fixing merge conflict-1

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-11-12 21:55 UTC, sai-arigeli commented
> I thought of another change--since this changes the behavior of how falco reads rules files, you should bump the falco engine version here: https://github.com/falcosecurity/falco/blob/master/userspace/engine/falco_engine_version.h#L19. Can you increment it to 11?

@mstemm Fixed this!

2021-11-15 10:40 UTC, leogr commented
> > I thought of another change--since this changes the behavior of how falco reads rules files, you should bump the falco engine version here: https://github.com/falcosecurity/falco/blob/master/userspace/engine/falco_engine_version.h#L19. Can you increment it to 11?
> 
> @mstemm Fixed this!

Hey @sai-arigeli 

as per our policy, merge commits are not allowed. Could you use `git rebase` to fix this issue? Thanks in advance

2021-11-16 22:07 UTC, sai-arigeli commented
@mstemm @leogr Addressed the change requests.

2021-11-17 18:05 UTC, mstemm approved these changes

2021-11-17 18:05 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: 492d3631bcbc013216e768f3f89f738cff4d3e1e</details>

2021-11-18 08:10 UTC, leogr approved these changes
LGTM
/approve

2021-11-18 08:10 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco/pull/1780#pullrequestreview-809583018" title="Approved">leogr</a>*, *<a href="https://github.com/falcosecurity/falco/pull/1780#" title="Author self-approved">sai-arigeli</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/falco/blob/master/OWNERS)~~ [leogr]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-11-18 08:11 UTC, merged