Escape double-quotes in aws cloudtrail rule
falcosecurity/falco pull request #1874
Opened 2022-01-26 23:45 UTC by mstemm

The rule Delete Bucket Public Access Block has a predicate
`json.value[/requestParameters/publicAccessBlock]=""` to match
an event snippet like this:

```
			"requestParameters": {
				"publicAccessBlock": "",
```

The cloudtrail plugin properly returns `""` for this field, but the
yaml representation was a literal back-to-back quote, which gets
interpreted by the yaml parser to be an empty string.

Escaping the back-to-back quote fixes the ambiguity.

This is related to https://github.com/falcosecurity/plugins/issues/56. There were actually 3 fixes in plugins/libs/falco, so I won't directly link it here.

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

/kind rule-update

> /kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area engine

/area rules

> /area tests

> /area proposals

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2022-01-26 23:45 UTC, poiana commented
@mstemm: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-01-26 23:45 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco/pull/1874#" title="Author self-approved">mstemm</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[rules/OWNERS](https://github.com/falcosecurity/falco/blob/master/rules/OWNERS)~~ [mstemm]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-01-27 14:49 UTC, leogr requested changes
This solution will not address all cases.

The current implementation of the `json` plugin always [returns](https://github.com/falcosecurity/plugins/blob/f6b32ee7625ea95fe0739c21cbc05dda69d3ffc7/plugins/json/json.go#L133) the literal string as in JSON syntax (ie. all strings will be always double-quoted, see [here](https://github.com/valyala/fastjson/blob/6dae91c8e11a7fa6a257a550b75cba53ab81693e/parser.go#L596)). 

So the bug in the current implementation is that all strings contain unnecessary double quotes. Not only the empty string case is affected. Also, all other string comparisons are affected. For example, also this condition :point_down: won't be triggered.
https://github.com/falcosecurity/falco/blob/6a42f4a1333275dd43f844b326dae60316575a17/rules/aws_cloudtrail_rules.yaml#L52
(because the extracted string is `"Success"` and not `Success` as one would expect).

To fix the problem extracted strings should not contain any double-quote. Thus it should be fixed in the extraction phase and not here. 

We (@jasondellaluce, @FedeDP, and I) are addressing the problem directly in the `json` plugin.

2022-01-27 15:34 UTC, leogr commented
Probably superseded by https://github.com/falcosecurity/plugins/pull/59

2022-01-27 17:05 UTC, mstemm commented
Ok, I'll close this then.

2022-01-27 17:05 UTC, closed without merging