Fixed condition rule Launch Privileged Container
falcosecurity/falco pull request #2117
Opened 2022-07-07 14:53 UTC by Brucedh

This PR fixes the condition of the "Launch Privileged Container" by adding a whitelist of Red Hat images, to reduce the noise and false positives.

Signed-off-by: Alessandro Brucato <alessandro.brucato@sysdig.com>

**What type of PR is this?**

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

/kind rule-update

> /kind rule-create

**Any specific area of the project related to this PR?**

> /area build

> /area engine

/area rules

> /area tests

> /area proposals

**What this PR does / why we need it**:
This PR fixes the condition of the "Launch Privileged Container" by adding a whitelist of Red Hat images, to reduce the noise and false positives.

**Which issue(s) this PR fixes**:
Too much noise and false positives.

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
rule(Launch Privileged Container): Fixed condition for the rules to address noise
```

2022-07-07 14:53 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco/pull/2117#" title="Author self-approved">Brucedh</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **mstemm** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @mstemm` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco).

<details open>
Needs approval from an approver in each of these files:

- **[rules/OWNERS](https://github.com/falcosecurity/falco/blob/master/rules/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["mstemm"]} -->

2022-07-07 15:08 UTC, darryk10 requested changes
Hi @Brucedh,
Thanks for the PR I just proposed some changes but overall it looks good to reduce the false positive on those images.

2022-07-07 15:09 UTC, poiana commented
@darryk10: changing LGTM is restricted to collaborators

<details>

In response to [this](https://github.com/falcosecurity/falco/pull/2117#pullrequestreview-1031735116):

>Hi @Brucedh,
>Thanks for the PR I just proposed some changes but overall it looks good to reduce the false positive on those images.


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-07-11 14:40 UTC, poiana commented
@darryk10: changing LGTM is restricted to collaborators

<details>

In response to [this](https://github.com/falcosecurity/falco/pull/2117#pullrequestreview-1034460293):

>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-07-13 08:35 UTC, Brucedh commented
Hi, thanks for the suggestions, I pushed all of them

2022-07-13 08:36 UTC, Brucedh commented
/assign @Kaizhe

2022-07-13 09:28 UTC, jasondellaluce commented
/ok-to-test

2022-07-13 09:29 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: 3d8c24e2c75865243e4b6422ee1f4f454bac232c</details>

2022-07-13 09:54 UTC, leogr approved these changes
LGTM

2022-07-13 09:54 UTC, merged