Add rule to detect bypass by symlink files
falcosecurity/falco pull request #2202
Opened 2022-09-13 04:27 UTC by hi120ki

Signed-off-by: Hi120ki <12624257+hi120ki@users.noreply.github.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> /kind release

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

> /kind rule-update

/kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area engine

/area rules

> /area tests

> /area proposals

> /area CI

**What this PR does / why we need it**:

In some falco rules, such as detecting specific file access, are using `fd.name`.

For exameple, the rule `Read sensitive file trusted after startup` detects to access sensitive files, like `/etc/shadow`, `/etc/pam.conf`, by `fd.name in (sensitive_file_names)`.

But in linux filesystem, there are some already defined symlink files, such as `/var/spool/cron/crontabs`, this is linked into `/etc/crontabs` directory.

Then using these symlink files, it is posssible to bypass falco detection.

```
$ docker run --rm -itd --name alpine alpine:latest
$ docker exec -it alpine ash
/ # cat /etc/shadow
root:*::0:::::
...
```

It cause `Warning Sensitive file opened for reading by non-trusted program`.

But running this command, there is no detection, successfully bypassed!

```
/ # cat /var/spool/cron/crontabs/../shadow
root:*::0:::::
...
```

How this symlink file based bypass method works:

```
/var/spool/cron/crontabs/ = /etc/crontabs
/var/spool/cron/crontabs/../ = /etc/
/var/spool/cron/crontabs/../shadow = /etc/shadow
```

Then, using other defined symlink file `/dev/fd`, is linked into `/proc/self/fd`, can bypass the rule `Read environment variable from /proc files` (in PR #2193, approved and waiting merge) like this command

```
/ # cat /dev/fd/../environ
HOSTNAME=...
```

Then, a more general method is using `/proc/self/root -> /`, is pointed out by [@mrtc0](https://twitter.com/mrtc0) in [How to Bypass Falco](https://blog.ssrf.in/post/how-to-bypass-falco/), can be used like this

```
/ # cat /proc/self/root/etc/shadow
root:*::0:::::
...
```

Related to `/proc/self/root`, there is `/proc/self/cwd -> (proccess dir)`.

```
/ # cat /proc/self/cwd/etc/shadow
root:*::0:::::
...
/ # cat /proc/self/cwd/../etc/shadow
/ # cat /proc/self/cwd/../../etc/shadow
```

To detect these bypass method, I propose this rule.

```yaml
- rule: Detection bypass by symlinked files
  desc: An attempt to bypass fd.name based rules by existing symlink files
  condition: >
    (fd.nameraw glob '*/proc*/root/*')
    or (fd.nameraw glob '*/proc*/cwd/*')
    or (fd.nameraw glob '*/dev*/fd/*..*')
    or (fd.nameraw glob '*/var*/spool*/cron*/crontabs/*..*')
  enabled: true
  output: >
    Detection bypass by symlinked files (user=%user.name user_loginuid=%user.loginuid program=%proc.name
    command=%proc.cmdline file=%fd.name parent=%proc.pname gparent=%proc.aname[2] ggparent=%proc.aname[3] gggparent=%proc.aname[4] container_id=%container.id image=%container.image.repository)
  priority: Alert
  tags: [filesystem]
```

> `/dev/fd` and `/var/spool/cron/crontabs` are used by ordinary process, add `*..*` to the end of glob match text for reducing false positive.

> Memo: why my proposed rule is created `fd.nameraw` insted of `fd.name`
>
> If we run command `cat /proc/self/root/../etc/shadow`, falco probe record `openat` syscall with argument `/proc/self/root/../etc/shadow`
>
> and falco normalize argument path by `falco-lib` and generate `fd.name = /proc/self/etc/shadow` (`root` is disappear). So, it is impossible to detect by `fd.name`.

I tested this rule by these commands on alpine and ubuntu latest image, if you find corner cases, please tell me.

```
cat /proc/self/root/etc/shadow
cat /proc/self/./root/etc/shadow
cat /proc/self/root/../etc/shadow
cat ../proc/self/root/etc/shadow
cat /proc/self/cwd/../../etc/shadow
cat /dev/fd/../environ
cat /dev/./fd/../environ
cat ../dev/fd/../environ
cat /var/spool/cron/crontabs/../shadow
cat /var/spool/./cron/crontabs/../shadow
cat ../var/spool/cron/crontabs/../shadow
```

This bypass technique has huge impact to falco detection. The above, I only show bypassing `Sensitive file opened for reading by non-trusted program` and `Read environment variable from /proc files`, but there are more rules that can bypass.

I'm now looking for other symlink files that can bypass falco rules, I will create another PR to add that after this PR is merged.

I'm waiting for your comments on this bypass technique and my proposed rules.

Thank you.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Add rule to detect bypass by symlink files
```

2022-09-13 04:27 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco/pull/2202#" title="Author self-approved">hi120ki</a>*
**Once this PR has been reviewed and has the lgtm label**, please assign mstemm for approval by writing `/assign @mstemm` in a comment. For more information see:[The Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco).

<details open>
Needs approval from an approver in each of these files:

- **[rules/OWNERS](https://github.com/falcosecurity/falco/blob/master/rules/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["mstemm"]} -->

2022-09-13 08:21 UTC, jasondellaluce commented
/ok-to-test

/milestone 0.33.0

2022-09-16 10:50 UTC, leogr commented
cc @darryk10

2022-09-16 16:05 UTC, darryk10 reviewed
Hi @hi120ki, 
Thanks again for the contribution. I agree the rule is pretty useful and I proposed a few changes based on the known use cases and trying to reduce the FPs. 
However since the operator `nameraw` is available from the next version I couldn't test it broadly and in live environment so not really able to evaluate the amount of false positive this rule might generate in live environments.
In this case I suggest to wait for the release of the new operator and we can all test it properly to make sure to avoid FPs and general noise.

2022-09-19 01:43 UTC, hi120ki commented on rules/falco_rules.yaml
> +    or (fd.nameraw glob '*/var*/spool*/cron*/crontabs/*..*')
@darryk10 Thank you for suggestion. I agree your modification about L.3209 and L.3210.

But about L.3211 and L.3212, it is impossible to detect these commands.

```
cat /dev/fd/../environ
cat ../dev/fd/../environ
cat /var/spool/./cron/crontabs/../shadow
cat /var/spool/../spool/cron/crontabs/../shadow
cat /var/spool/cron/../cron/crontabs/../shadow
```

Then about L.3211 and L.3212, I propose previous condition.

2022-09-19 08:24 UTC, leogr commented
Hey @hi120ki 

Could you also rebase this PR, please? :pray:

2022-09-19 09:03 UTC, leogr commented
/reopen

2022-09-19 09:03 UTC, poiana commented
@leogr: Failed to re-open PR: state cannot be changed. There are no new commits on the hi120ki:add-detection-bypass-by-symlinked-files branch.

<details>

In response to [this](https://github.com/falcosecurity/falco/pull/2202#issuecomment-1250753879):

>/reopen


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-09-19 09:36 UTC, leogr commented
/reopen

2022-09-19 09:36 UTC, poiana commented
@leogr: Reopened this PR.

<details>

In response to [this](https://github.com/falcosecurity/falco/pull/2202#issuecomment-1250792308):

>/reopen


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-09-19 09:36 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco/pull/2202#" title="Author self-approved">hi120ki</a>*
**Once this PR has been reviewed and has the lgtm label**, please assign mstemm for approval by writing `/assign @mstemm` in a comment. For more information see:[The Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco).

<details open>
Needs approval from an approver in each of these files:

- **[rules/OWNERS](https://github.com/falcosecurity/falco/blob/master/rules/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["mstemm"]} -->

2022-09-19 09:36 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco/pull/2202#" title="Author self-approved">hi120ki</a>*
**Once this PR has been reviewed and has the lgtm label**, please assign mstemm for approval by writing `/assign @mstemm` in a comment. For more information see:[The Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco).

<details open>
Needs approval from an approver in each of these files:

- **[rules/OWNERS](https://github.com/falcosecurity/falco/blob/master/rules/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["mstemm"]} -->

2022-10-12 13:52 UTC, jasondellaluce commented
/milestone 0.34.0

2022-10-20 14:36 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/.github/blob/main/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [572ed22](https://github.com/falcosecurity/falco/commits/572ed22e2c56842837b959bc4900624e442f7d4c) Merge branch 'falcosecurity:master' into add-detection-bypass-by-symlinked-files

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2022-10-20 14:36 UTC, poiana commented
@hi120ki: Adding label `do-not-merge/contains-merge-commits` because PR contains merge commits, which are not allowed in this repository.
Use `git rebase` to reapply your commits on top of the target branch. Detailed instructions for doing so can be found [here](https://git.k8s.io/community/contributors/guide/github-workflow.md#4-keep-your-branch-in-sync).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-10-20 14:40 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/.github/blob/main/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [572ed22](https://github.com/falcosecurity/falco/commits/572ed22e2c56842837b959bc4900624e442f7d4c) Merge branch 'falcosecurity:master' into add-detection-bypass-by-symlinked-files

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2022-10-20 14:42 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/.github/blob/main/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [572ed22](https://github.com/falcosecurity/falco/commits/572ed22e2c56842837b959bc4900624e442f7d4c) Merge branch 'falcosecurity:master' into add-detection-bypass-by-symlinked-files
- [253a194](https://github.com/falcosecurity/falco/commits/253a19404f8f83f37031ae93d0730cfc7621f8da) Merge branch 'add-detection-bypass-by-symlinked-files' of ssh://github.com/hi120ki/falco into add-detection-bypass-by-symlinked-files

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2022-10-20 14:52 UTC, hi120ki commented
@darryk10 I have committed part of your suggestion.

Your suggestion about this

```yaml
    or (fd.nameraw glob '*/dev/*/fd/*..*')
    or (fd.nameraw glob '*/var/spool/cron/crontabs/*..*')
```

make it impossible to detect these commands.

```
cat /dev/fd/../environ
cat ../dev/fd/../environ
cat /var/spool/./cron/crontabs/../shadow
cat /var/spool/../spool/cron/crontabs/../shadow
cat /var/spool/cron/../cron/crontabs/../shadow
```

Please refer <https://github.com/falcosecurity/falco/pull/2202#discussion_r973168239>
Thank you!

2022-11-04 07:46 UTC, darryk10 commented
Thanks @hi120ki . will test this broadly now that the new falco release is out. 
Thanks

2022-11-24 18:26 UTC, darryk10 commented
Hi @hi120ki do you think we can add something in the condition for evt.type? What you think about `open_read` macro?

2022-11-24 23:45 UTC, hi120ki commented
@darryk10 I write this rule with referring a rule `Directory traversal monitored file read`.
Then I only checked `directory_traversal` macro and forgot to add some `evt.type`.
I agree with adding some `evt.type`, and we should choose `open_read` or `(open_read or open_file_failed)`.

Basically, some attackers try to read files that is not allowed by file permission, so how about add `(open_read or open_file_failed)`?
Could you give some comments?

Thank you.

2022-11-29 10:45 UTC, darryk10 commented
Hi @hi120ki I agree we should add both `open_read or open_file_failed`. If you can add to the rule would be awesome.
Thanks

2022-11-29 11:56 UTC, Biagio-Dipalma commented
Hey @hi120ki I've made some tests with your condition and I suggest to change paths matched and make them more specific since I saw some noise. 
I came up with this condition:
```
- rule: Detection bypass by symlinked files
  desc: An attempt to bypass fd.name based rules by existing symlink files
  condition: >
    (open_read or open_file_failed) and
    ((fd.nameraw glob '/proc/root/*/*..*')
    or (fd.nameraw glob '/proc/self/*/*..*')
    or (fd.nameraw glob '*/proc*/cwd/*')
    or (fd.nameraw glob '*/dev*/fd/*..*')
    or (fd.nameraw glob '*/var*/spool*/cron*/crontabs/*..*'))
  enabled: true
  output: >
    Detection bypass by symlinked files (user=%user.name user_loginuid=%user.loginuid program=%proc.name
    command=%proc.cmdline file=%fd.name parent=%proc.pname gparent=%proc.aname[2] ggparent=%proc.aname[3] gggparent=%proc.aname[4] container_id=%container.id image=%container.image.repository)
  priority: Alert
  tags: [filesystem]
```
What changes?

- Added `open_read or open_file_failed` as @darryk10 suggests
- Replaced `(fd.nameraw glob '*/proc/*/root/*')` with `(fd.nameraw glob '/proc/root/*/*..*') or (fd.nameraw glob '/proc/self/*/*..*')` to reduce false positives.

I know that we will miss some use cases and commands but we need to make the rule less noisy and more effective.
What do you think?

2022-11-30 16:04 UTC, hi120ki commented
@Biagio-Dipalma Thank you for reply!
We should add `open_read or open_file_failed` as @darryk10 suggests.

About `(fd.nameraw glob '/proc/root/*/*..*') or (fd.nameraw glob '/proc/self/*/*..*')`, I think there are `/proc/self/root/` or `/proc/1/root/` (=`/proc/[pid]/root/`) directories, not `/proc/root`.
So, `(fd.nameraw glob '/proc/self/*/*..*')` works to detect specific cases, but `(fd.nameraw glob '/proc/root/*/*..*')` doesn't work.

And most of cases, `..` is not used because `/proc/self/root` is equal to root directory and attackers can point out any directories without using `..`

Attackers can access `/etc/shadow` with bypassing like these cases

```
1) cat /proc/self/root/etc/shadow
2) cat /proc/self/./root/etc/shadow
3) cat /proc/self/../self/root/etc/shadow
4) cat ../proc/self/root/etc/shadow
5) cat /proc/./self/root/./etc/shadow
6) cat /proc/1/root/etc/shadow
7) cat /proc/1/./root/etc/shadow
8) cat /proc/1/../self/root/etc/shadow
9) cat ../proc/1/root/etc/shadow
10) cat /proc/./1/root/./etc/shadow
```

First, base condition should be `(fd.nameraw glob '/proc/self/root/*') or (fd.nameraw glob '/proc/1/root/*')`
Next, `self` or `1` can be bypassed by using `/./` or `self/../self`,`(fd.nameraw glob '/proc/*/root/*')`
Then, `/proc` can be bypassed by using `../proc`, `(fd.nameraw glob '*/proc/*/root/*')`

This is how l made this condition, we can choose specific techniques from this to make condition more specific.

Could you tell me what kind of FPs are detected when condition is `(fd.nameraw glob '*/proc/*/root/*')`? 
Presumably it is difficult to detect all cases without any FPs, so we should delete some cases similer to FP's payload and create fixed condition.

2022-12-16 11:23 UTC, leogr commented
/milestone 0.35.0

2023-03-16 15:58 UTC, poiana commented
Issues go stale after 90d of inactivity.

Mark the issue as fresh with `/remove-lifecycle stale`.

Stale issues rot after an additional 30d of inactivity and eventually close.

If this issue is safe to close now please do so with `/close`.

Provide feedback via https://github.com/falcosecurity/community.

/lifecycle stale

2023-03-19 15:01 UTC, leogr requested changes
Could you migrate this PR to https://github.com/falcosecurity/rules, please?

Thanks

2023-03-19 15:01 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco/pull/2202#" title="Author self-approved">hi120ki</a>*
**Once this PR has been reviewed and has the lgtm label**, please assign fededp for approval. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falco/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["fededp"]} -->

2023-04-18 19:27 UTC, poiana commented
Stale issues rot after 30d of inactivity.

Mark the issue as fresh with `/remove-lifecycle rotten`.

Rotten issues close after an additional 30d of inactivity.

If this issue is safe to close now please do so with `/close`.

Provide feedback via https://github.com/falcosecurity/community.

/lifecycle rotten

2023-04-27 09:50 UTC, leogr commented
> Could you migrate this PR to https://github.com/falcosecurity/rules, please?
> 
> Thanks

Hey @hi120ki 

Rules files have been moved to https://github.com/falcosecurity/rules. Please, reopen this PR there :pray: 

/close

2023-04-27 09:50 UTC, closed without merging

2023-04-27 09:50 UTC, poiana commented
@leogr: Closed this PR.

<details>

In response to [this](https://github.com/falcosecurity/falco/pull/2202#issuecomment-1525309922):

>> Could you migrate this PR to https://github.com/falcosecurity/rules, please?
>> 
>> Thanks
>
>Hey @hi120ki 
>
>Rules files have been moved to https://github.com/falcosecurity/rules. Please, reopen this PR there :pray: 
>
>/close


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2023-04-29 14:32 UTC, hi120ki commented
@leogr Thanks! I created PR at https://github.com/falcosecurity/rules/pull/51 .
I apologize for the delay.

2023-05-03 07:12 UTC, leogr commented
Thank you!