Rule: PTRACE anti-debug attempt
falcosecurity/falco pull request #2227
Opened 2022-09-28 15:47 UTC by Brucedh

Signed-off-by: Alessandro Brucato <alessandro.brucato@sysdig.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> /kind release

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

> /kind rule-update

/kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area engine

/area rules

> /area tests

> /area proposals

> /area CI

**What this PR does / why we need it**:
The ptrace system call is used by debuggers, such as GDB, to examine a target process. Malicious programs will often try to prevent this by using the ptrace system call first, preventing other programs from using it on them. This rule detects that behavior. Legitimate processes may also do this for DRM or diagnostic purposes. 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
New rule to detect usages of the PTRACE system call with the PTRACE_TRACEME argument, indicating a program actively attempting to avoid debuggers attaching to the process.
```

2022-09-28 15:47 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco/pull/2227#" title="Author self-approved">Brucedh</a>*
**Once this PR has been reviewed and has the lgtm label**, please assign mstemm for approval by writing `/assign @mstemm` in a comment. For more information see:[The Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco).

<details open>
Needs approval from an approver in each of these files:

- **[rules/OWNERS](https://github.com/falcosecurity/falco/blob/master/rules/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["mstemm"]} -->

2022-09-28 15:59 UTC, jasondellaluce commented
/milestone 0.34.0

2022-11-04 07:48 UTC, darryk10 commented
@loresuso @Kaizhe can you provide your feedback for this rule as well?
We have tested the rule for a while and it looks pretty accurate withouf FPs. If you have any ways we can improve the rule to cover other use cases would be great.
Thanks

2022-12-15 11:58 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco/pull/2227#" title="Author self-approved">Brucedh</a>*
**Once this PR has been reviewed and has the lgtm label**, please assign mstemm for approval by writing `/assign @mstemm` in a comment. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco).

<details open>
Needs approval from an approver in each of these files:

- **[rules/OWNERS](https://github.com/falcosecurity/falco/blob/master/rules/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["mstemm"]} -->

2022-12-15 11:59 UTC, leogr commented
> @loresuso @Kaizhe can you provide your feedback for this rule as well? We have tested the rule for a while and it looks pretty accurate withouf FPs. If you have any ways we can improve the rule to cover other use cases would be great. Thanks

:+1: 

cc @loresuso @darryk10 @Kaizhe

2022-12-15 12:22 UTC, loresuso commented
My opinion on this is that this anti-debugging technique is the most simple one and most people know about it, and I think it is rarely used because it can be easily bypassed by simply patching calls to this syscall. 

I believe malware writers have many other options for anti-debugging, which are more meaningful to me, like timing analysis (if the process is being debugged, execution times will differ from normal execution flow) or just checking if parent process is a known debugger binary, which is also easy to implement like this one. Furthermore, as you pointed out, legitimate processes may use this. 

So what I think is that this rule triggering wouldn't be so much relevant for spotting malware, although it can be useful in some cases, I don't know if we want it to be in the default Falco ruleset.

2022-12-16 11:23 UTC, leogr commented
/milestone 0.35.0

2023-03-06 13:31 UTC, jasondellaluce commented
This needs to be ported to https://github.com/falcosecurity/rules

2023-03-08 17:47 UTC, leogr commented
> This needs to be ported to https://github.com/falcosecurity/rules

cc @darryk10 @loresuso

2023-03-19 17:29 UTC, leogr requested changes
Please, this PR needs to be ported to https://github.com/falcosecurity/rules

2023-03-19 17:29 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco/pull/2227#" title="Author self-approved">Brucedh</a>*
**Once this PR has been reviewed and has the lgtm label**, please assign fededp for approval. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falco/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["fededp"]} -->

2023-03-20 10:34 UTC, darryk10 commented
Due to what happened here https://github.com/falcosecurity/rules/pull/37/files I would revaluate this rule once the PR is merged and tested. @Brucedh feel free to start closing this here and open a new one in the new repo falcosecurity/rules.
Thanks

2023-03-28 09:37 UTC, Brucedh commented
Alright, I close this PR after having ported it to https://github.com/falcosecurity/rules/pull/40

2023-03-28 09:37 UTC, closed without merging