fixed the token-permission and pinned-dependencies issue
falcosecurity/falco pull request #3299
Opened 2024-08-17 20:00 UTC by harshitasao

/area CI

**What this PR does / why we need it**:
fixed the token-permission and pinned-dependencies issue which are reported by [scorecard](https://scorecard.dev/viewer/?uri=github.com/falcosecurity/falco).

**Which issue(s) this PR fixes**:
Part of #3297 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

2024-08-17 20:00 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco/pull/3299#" title="Author self-approved">harshitasao</a>*
**Once this PR has been reviewed and has the lgtm label**, please assign [jasondellaluce](https://github.com/jasondellaluce) for approval. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falco/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["jasondellaluce"]} -->

2024-08-17 20:03 UTC, FedeDP commented on .github/workflows/reusable_test_packages.yaml
> +        uses: falcosecurity/testing@32e319ae505fb330ae74db4502e605a5e517ff22 # main
Given this is our own repo we actually want to always point to latest main, not the current one. 
Can you revert this line?

2024-08-20 08:15 UTC, FedeDP commented on .github/workflows/reusable_test_packages.yaml
> +        uses: falcosecurity/testing@32e319ae505fb330ae74db4502e605a5e517ff22 # main
/hold

2024-08-20 08:16 UTC, FedeDP commented
/milestone 0.39.0

2024-08-23 11:58 UTC, sgaist requested changes

2024-08-23 11:58 UTC, sgaist commented on .github/workflows/reusable_build_docker.yaml
> +permissions:
To keep space coherency

```suggestion

permissions:
```

2024-08-23 11:58 UTC, sgaist commented on .github/workflows/codespell.yml
> +permissions:
To keep space coherency

```suggestion

permissions:
```

2024-08-28 22:17 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco/pull/3299#" title="Author self-approved">harshitasao</a>*
**Once this PR has been reviewed and has the lgtm label**, please ask for approval from [sgaist](https://github.com/sgaist). For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falco/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["sgaist"]} -->

2024-08-29 06:30 UTC, FedeDP approved these changes
/approve

2024-08-29 06:30 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco/pull/3299#pullrequestreview-2267792721" title="Approved">FedeDP</a>*, *<a href="https://github.com/falcosecurity/falco/pull/3299#" title="Author self-approved">harshitasao</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/falco/blob/master/OWNERS)~~ [FedeDP]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2024-08-29 06:30 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: b23686b642e23ec0fd0ddab9830f650f75d1b07d</details>

2024-08-29 06:30 UTC, FedeDP commented
/unhold

2024-09-04 12:13 UTC, FedeDP commented
cc @sgaist care to re-review? :D

2024-09-04 17:52 UTC, sgaist commented
@FedeDP AFAICT, there's still the `uses: falcosecurity/testing@32e319ae505fb330ae74db4502e605a5e517ff22` line that you wanted reverted that is still present. Did you change your mind about it ?

2024-09-04 19:20 UTC, FedeDP commented
@sgaist i double checked and it seems reverted to me! Am I missing anything? 😆

2024-09-04 19:59 UTC, sgaist approved these changes
My bad, I mixed that with the actions-github-release version.

2024-09-04 20:00 UTC, merged

2024-09-10 08:28 UTC, FedeDP commented
This PR broke master CI triggering :/ don't know why.